import { DataSource } from 'typeorm';
import { PlaceOption } from 'modules/place-options/place-option.entity';
import { Seeder } from 'typeorm-extension';
import {
  PlaceOptionType,
  PlaceOptionCategory,
} from '@/modules/place-options/place-option-type';

export const placeOptionSeeds: Partial<PlaceOption>[] = [
  // Cuisine Types
  {
    name: 'French Cuisine',
    slug: 'french-cuisine',
    description: 'Classic French culinary traditions',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Indian Cuisine',
    slug: 'indian-cuisine',
    description: 'Traditional Indian dishes and flavors',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Japanese Cuisine',
    slug: 'japanese-cuisine',
    description: 'Authentic Japanese food including sushi, ramen, and more',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Mexican Cuisine',
    slug: 'mexican-cuisine',
    description: 'Traditional Mexican dishes and flavors',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Vietnamese Cuisine',
    slug: 'vietnamese-cuisine',
    description: 'Authentic Vietnamese dishes',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Italian Cuisine',
    slug: 'italian-cuisine',
    description: 'Classic Italian dishes including pasta and pizza',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Chinese Cuisine',
    slug: 'chinese-cuisine',
    description: 'Traditional Chinese dishes from various regions',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Thai Cuisine',
    slug: 'thai-cuisine',
    description: 'Authentic Thai dishes with bold flavors',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Mediterranean Cuisine',
    slug: 'mediterranean-cuisine',
    description:
      'Mediterranean dishes from Greece, Turkey, and the Middle East',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'American Cuisine',
    slug: 'american-cuisine',
    description: 'Classic American dishes and comfort food',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Korean Cuisine',
    slug: 'korean-cuisine',
    description: 'Traditional Korean dishes including BBQ and kimchi',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Spanish Cuisine',
    slug: 'spanish-cuisine',
    description: 'Traditional Spanish dishes and tapas',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Greek Cuisine',
    slug: 'greek-cuisine',
    description: 'Authentic Greek dishes and Mediterranean flavors',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Lebanese Cuisine',
    slug: 'lebanese-cuisine',
    description: 'Traditional Lebanese dishes and mezze',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Turkish Cuisine',
    slug: 'turkish-cuisine',
    description: 'Authentic Turkish dishes and kebabs',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'Brazilian Cuisine',
    slug: 'brazilian-cuisine',
    description: 'Traditional Brazilian dishes and churrasco',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'Moroccan Cuisine',
    slug: 'moroccan-cuisine',
    description: 'Authentic Moroccan dishes with rich spices',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'German Cuisine',
    slug: 'german-cuisine',
    description: 'Traditional German dishes and beer hall fare',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 18,
  },
  {
    name: 'British Cuisine',
    slug: 'british-cuisine',
    description: 'Classic British dishes and pub food',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 19,
  },
  {
    name: 'Fusion Cuisine',
    slug: 'fusion-cuisine',
    description: 'Creative fusion of different culinary traditions',
    category: PlaceOptionCategory.CUISINE_TYPE,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 20,
  },

  // Dining Options
  {
    name: 'Dine-in',
    slug: 'dine-in',
    description: 'Dining available on-site at the restaurant',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Takeaway',
    slug: 'takeaway',
    description: 'Food available for takeout',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Delivery',
    slug: 'delivery',
    description: 'Food delivery service available',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Curbside Pickup',
    slug: 'curbside-pickup',
    description: 'Curbside pickup service available',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Catering',
    slug: 'catering',
    description: 'Catering services available for events',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Drive-through',
    slug: 'drive-through',
    description: 'Drive-through service available',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Outdoor Seating',
    slug: 'outdoor-seating',
    description: 'Outdoor dining area available',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Reservations',
    slug: 'reservations',
    description: 'Table reservations accepted',
    category: PlaceOptionCategory.DINING_OPTION,
    entityType: PlaceOptionType.RESTAURANT,
    isActive: true,
    sortOrder: 8,
  },

  // Product Categories (for Shopping)
  {
    name: "Men's Clothing",
    slug: 'mens-clothing',
    description: 'Clothing and apparel for men',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Groceries',
    slug: 'groceries',
    description: 'Food and grocery items',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Electronic devices and gadgets',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Supermarket',
    slug: 'supermarket',
    description: 'Supermarket and general merchandise',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Beauty Products',
    slug: 'beauty-products',
    description: 'Cosmetics and beauty products',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Books',
    slug: 'books',
    description: 'Books and literature',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: "Women's Clothing",
    slug: 'womens-clothing',
    description: 'Clothing and apparel for women',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: "Children's Clothing",
    slug: 'childrens-clothing',
    description: 'Clothing and apparel for children',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Shoes',
    slug: 'shoes',
    description: 'Footwear for all ages',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Fashion accessories and jewelry',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Home decor and garden supplies',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Sports equipment and outdoor gear',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Toys & Games',
    slug: 'toys-games',
    description: 'Toys, games, and entertainment',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Health & Personal Care',
    slug: 'health-personal-care',
    description: 'Health and personal care products',
    category: PlaceOptionCategory.PRODUCT_CATEGORY,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 14,
  },

  // Brands (for Shopping)
  {
    name: 'Apple',
    slug: 'apple',
    description: 'Apple products and accessories',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Samsung',
    slug: 'samsung',
    description: 'Samsung products and electronics',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Nike',
    slug: 'nike',
    description: 'Nike athletic wear and footwear',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Zara',
    slug: 'zara',
    description: 'Zara fashion and clothing',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'H&M',
    slug: 'h-m',
    description: 'H&M fashion and clothing',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Adidas',
    slug: 'adidas',
    description: 'Adidas athletic wear and footwear',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Sony',
    slug: 'sony',
    description: 'Sony electronics and entertainment',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'LG',
    slug: 'lg',
    description: 'LG electronics and appliances',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'Puma',
    slug: 'puma',
    description: 'Puma athletic wear and footwear',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Uniqlo',
    slug: 'uniqlo',
    description: 'Uniqlo clothing and apparel',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Gucci',
    slug: 'gucci',
    description: 'Gucci luxury fashion',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Prada',
    slug: 'prada',
    description: 'Prada luxury fashion',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Chanel',
    slug: 'chanel',
    description: 'Chanel luxury fashion and beauty',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Lululemon',
    slug: 'lululemon',
    description: 'Lululemon athletic apparel',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Under Armour',
    slug: 'under-armour',
    description: 'Under Armour athletic wear',
    category: PlaceOptionCategory.BRAND,
    entityType: PlaceOptionType.SHOPPING,
    isActive: true,
    sortOrder: 15,
  },
];

export default class PlaceOptionSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<void> {
    const placeOptionRepository = dataSource.getRepository(PlaceOption);

    console.log('🟢 Seeding place options...');

    for (const placeOptionData of placeOptionSeeds) {
      const existingPlaceOption = await placeOptionRepository.findOne({
        where: { slug: placeOptionData.slug },
      });

      if (!existingPlaceOption) {
        const placeOption = placeOptionRepository.create(placeOptionData);
        await placeOptionRepository.save(placeOption);
        console.log(
          `✅ Created place option [${placeOptionData.category}]: ${placeOptionData.name}`,
        );
      } else {
        console.log(`⏭️  Place option already exists: ${placeOptionData.name}`);
      }
    }

    console.log('🎉 Place option seeding completed!');
  }
}
